import { Inter } from "next/font/google";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.css';
import ScrollToTop from "@/utils/ScrollToTop";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "BAZAR",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa">
      <body className={inter.className}>
        {children}
        <ScrollToTop/>
        </body>
    </html>
  );
}
